### ISSUE TITLE
New Description Detail [][7]

### ISSUE THREAD

**Issue by LeviTamiozzo** [HA-Team/duit#18]
**Tasks**
- [x] Subtitle
- [x] Operation Type Card
- [x] Created At
- [x] Title
- [x] Full Description
- [x] Features Icons
- [x] General Environments
- [x] Location

**Comment by tomyo** [comment]
- [x] Reducir la niebla a las últimas 2 o 3 líneas solamente en la descripción.
  La niebla es sólo un hint para avisa que hay más, pero debería poder leerse todo lo que se muestra en pantalla cómodamente. 
Actualmente está así:
![image](https://user-images.githubusercontent.com/708569/79662042-c193b280-81b4-11ea-9991-3734293b1596.png)

Así me gustaría:
![image](https://user-images.githubusercontent.com/708569/79663506-2fd87500-81b5-11ea-808c-5172aa44a3c3.png)

![image](https://user-images.githubusercontent.com/708569/79663612-37981980-81b5-11ea-80ff-33ed486a758b.png)

**Comment by tomyo** [comment]
- [x] Arreglar los íconos del resumen de las características.

![image](https://user-images.githubusercontent.com/708569/79664182-5f877d00-81b5-11ea-9847-61e08c27993a.png)
